name: Node.js CI
on: [push]

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "clone and checkout git repo"
        uses: actions/checkout@v4
        #run: | 
        #  git clone https://github.com/JonasBa97/GitHub_Actions.git
        #  git fetch --all
        #  git checkout master
      
      - name: "Node.js 18 installieren"
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        #run: | 
        #  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash
        #  sudo apt-get install -y nodejs
        #  node -v
        #  npm -v

      # Variablen
      - name: "echo NODE_ENV"
        run: |
          echo $NODE_ENV
        #  echo ${{ vars.DOCKERHUB_USERNAME }}
        #  echo ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        #with:
        #  username: ${{ vars.DOCKERHUB_USERNAME }}
        #  password: ${{ secrets.DOCKERHUB_TOKEN }}